# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
#org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
#org.gradle.configureondemand=true
loom.ignoreDependencyLoomVersionValidation=true

# Mod properties
mod.version=2.0.0
mod.group=cc.cassian
mod.id=comfortable_campfires
mod.name=comfortable Campfires

# Used for the mod metadata
mod.mc_dep_fabric=[VERSIONED]
mod.mc_dep_forgelike=[VERSIONED]
# Used for the release title. I.e. '1.20.x'
mod.mc_title=[VERSIONED]
# Space separated versions for publishing. I.e. '1.20, 1.20.1'
mod.mc_targets=[VERSIONED]

# Mod setup
deps.mixin_extras=0.4.1
deps.fabric_loader=0.18.4
deps.neoforge_loader=[VERSIONED]
deps.kaleido=0.3.3+1.3.2
deps.fabric_asm=v2.3

# Mod dependencies
deps.fabric_api_version=[VERSIONED]
deps.cloth_version=[VERSIONED]
deps.fd=[VERSIONED]
deps.modmenu_version=[VERSIONED]

# Publishing
publish.modrinth=lOZBoyio
publish.curseforge=1172718