modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/cassiancc/Comfortable-Campfires/issues"
license = "MIT"

[[mods]]
modId = "comfortable_campfires"
version = "${version}"
displayName = "Comfortable Campfires"
authors = "cassiancc"
description = '''
Sitting by the campfire is now just a little more comfortable. Lit campfires now give nearby players Regeneration or Farmer's Delight's Comfort.
'''
logoFile = "icon.png"

[[dependencies.comfortable_campfires]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.comfortable_campfires]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

["lithium:options"]
"mixin.world.block_entity_ticking.sleeping.campfire" = false
